version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - "8123:8123"
    network_mode: host
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:                 # host 네트워크가 아니라 bridge일 때만 열 필요 있음
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    restart: unless-stopped
    privileged: true
    volumes:
      - ./zigbee2mqtt/data:/app/data
    environment:
      - TZ=Asia/Seoul
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB:/dev/ttyACM0  # 자신의 경로로 교체
    network_mode: host